
import { Product, Sales, Invoice, Supplier, User, ItemCategory } from './types';

export const categories: ItemCategory[] = [
    { id: 'cat-1', name: 'STRIPLIGHT', description: 'Various types of LED striplights.', createdAt: new Date().toISOString() },
    { id: 'cat-2', name: 'POWER SUPPLY', description: 'Power supplies for LED lighting.', createdAt: new Date().toISOString() },
    { id: 'cat-3', name: 'GENERAL LIGHTING', description: 'General purpose lighting fixtures.', createdAt: new Date().toISOString() },
    { id: 'cat-4', name: 'ALUMINIUM PROFILE', description: 'Aluminium profiles for LED strips.', createdAt: new Date().toISOString() },
];

export const products: Product[] = [
    {
        id: "PROD-2024-001",
        productCode: "PROD-2024-001",
        name: "High-Density LED Striplight 240L",
        category: "STRIPLIGHT",
        sku: "LED-HD-240-24",
        description: "High-density flexible LED striplight with 240 LEDs per meter. Provides bright, even illumination.",
        price: 150.00,
        stock: 120,
        reOrderLevel: 20,
        supplier: "LED Innovations Inc.",
        status: "In Stock",
        createdAt: "2024-05-01T10:00:00Z",
        modifiedAt: "2024-05-20T14:30:00Z",
        productImage: "https://placehold.co/300x300.png",
        uom: "roll",
        expiryDateTracking: false,
        ledQty: 240,
        voltage: 24,
        wattage: 19.2,
        meters: 5,
        location: "Warehouse A, Shelf 1"
    },
    {
        id: "PROD-2024-002",
        productCode: "PROD-2024-002",
        name: "Standard LED Striplight 120L",
        category: "STRIPLIGHT",
        sku: "LED-STD-120-12",
        description: "Standard density flexible LED striplight with 120 LEDs per meter. Good for general accent lighting.",
        price: 85.00,
        stock: 250,
        reOrderLevel: 50,
        supplier: "LED Innovations Inc.",
        status: "In Stock",
        createdAt: "2024-05-02T11:00:00Z",
        modifiedAt: "2024-05-21T15:00:00Z",
        productImage: "https://placehold.co/300x300.png",
        uom: "roll",
        expiryDateTracking: false,
        ledQty: 120,
        voltage: 12,
        wattage: 9.6,
        meters: 5,
        location: "Warehouse A, Shelf 1"
    },
    {
        id: "PROD-2024-003",
        productCode: "PROD-2024-003",
        name: "Waterproof Power Supply 100W",
        category: "POWER SUPPLY",
        sku: "PSU-WP-100-24",
        description: "100W, 24V waterproof power supply unit, suitable for outdoor LED installations. IP67 rated.",
        price: 750.00,
        stock: 50,
        reOrderLevel: 10,
        supplier: "Power Solutions Co.",
        status: "In Stock",
        createdAt: "2024-04-15T09:30:00Z",
        modifiedAt: "2024-05-18T12:00:00Z",
        productImage: "https://placehold.co/300x300.png",
        uom: "pcs",
        expiryDateTracking: false,
        ledQty: 0,
        voltage: 24,
        wattage: 100,
        meters: 0,
        location: "Warehouse B, Shelf 3"
    },
    {
        id: "PROD-2024-004",
        productCode: "PROD-2024-004",
        name: "Recessed Aluminium Profile 2m",
        category: "ALUMINIUM PROFILE",
        sku: "ALU-REC-2M",
        description: "2-meter long recessed aluminium profile for a clean, professional installation of LED strips.",
        price: 250.00,
        stock: 15,
        reOrderLevel: 20,
        supplier: "AluPro Extrusions",
        status: "Low Stock",
        createdAt: "2024-03-20T16:00:00Z",
        modifiedAt: "2024-05-22T09:00:00Z",
        productImage: "https://placehold.co/300x300.png",
        uom: "pcs",
        expiryDateTracking: false,
        ledQty: 0,
        voltage: 0,
        wattage: 0,
        meters: 2,
        location: "Warehouse C, Rack 2"
    },
    {
        id: "PROD-2024-005",
        productCode: "PROD-2024-005",
        name: "LED Downlight 12W",
        category: "GENERAL LIGHTING",
        sku: "GEN-DL-12W-WW",
        description: "12W recessed LED downlight, Warm White (3000K). Energy efficient and long-lasting.",
        price: 320.00,
        stock: 0,
        reOrderLevel: 25,
        supplier: "Bright Home Lighting",
        status: "Out of Stock",
        createdAt: "2024-04-25T13:00:00Z",
        modifiedAt: "2024-05-19T17:00:00Z",
        productImage: "https://placehold.co/300x300.png",
        uom: "pcs",
        expiryDateTracking: false,
        ledQty: 1,
        voltage: 220,
        wattage: 12,
        meters: 0,
        location: "Warehouse B, Shelf 1"
    },
    {
        id: "PROD-2024-006",
        productCode: "PROD-2024-006",
        name: "Compact Power Supply 60W",
        category: "POWER SUPPLY",
        sku: "PSU-COMP-60-12",
        description: "60W, 12V compact power supply unit, ideal for indoor use with limited space.",
        price: 450.00,
        stock: 80,
        reOrderLevel: 15,
        supplier: "Power Solutions Co.",
        status: "In Stock",
        createdAt: "2024-05-10T10:30:00Z",
        modifiedAt: "2024-05-20T11:00:00Z",
        productImage: "https://placehold.co/300x300.png",
        uom: "pcs",
        expiryDateTracking: false,
        ledQty: 0,
        voltage: 12,
        wattage: 60,
        meters: 0,
        location: "Warehouse B, Shelf 3"
    },
    {
        id: "PROD-2024-007",
        productCode: "PROD-2024-007",
        name: "Surface-mounted Aluminium Profile 1m",
        category: "ALUMINIUM PROFILE",
        sku: "ALU-SUR-1M",
        description: "1-meter surface-mounted aluminium profile with diffuser. Easy to install.",
        price: 180.00,
        stock: 300,
        reOrderLevel: 50,
        supplier: "AluPro Extrusions",
        status: "In Stock",
        createdAt: "2024-05-05T14:00:00Z",
        modifiedAt: "2024-05-21T10:00:00Z",
        productImage: "https://placehold.co/300x300.png",
        uom: "pcs",
        expiryDateTracking: false,
        ledQty: 0,
        voltage: 0,
        wattage: 0,
        meters: 1,
        location: "Warehouse C, Rack 1"
    },
    {
        id: "PROD-2024-008",
        productCode: "PROD-2024-008",
        name: "RGB LED Controller",
        category: "STRIPLIGHT",
        sku: "LED-RGB-CTRL-RF",
        description: "RF remote controller for RGB LED strips. Includes multiple color modes and brightness control.",
        price: 350.00,
        stock: 45,
        reOrderLevel: 10,
        supplier: "LED Innovations Inc.",
        status: "In Stock",
        createdAt: "2024-02-10T11:45:00Z",
        modifiedAt: "2024-05-15T18:00:00Z",
        productImage: "https://placehold.co/300x300.png",
        uom: "pcs",
        expiryDateTracking: false,
        ledQty: 0,
        voltage: 0,
        wattage: 0,
        meters: 0,
        location: "Warehouse A, Shelf 2"
    },
];

export const sales: Sales[] = [
    { id: "SALE-001", productId: "PROD-2024-001", productName: "High-Density LED Striplight 240L", customerName: "John Doe", date: "2024-05-20", quantity: 5, total: 750.00 },
    { id: "SALE-002", productId: "PROD-2024-002", productName: "Standard LED Striplight 120L", customerName: "Jane Smith", date: "2024-05-21", quantity: 10, total: 850.00 },
    { id: "SALE-003", productId: "PROD-2024-003", productName: "Waterproof Power Supply 100W", customerName: "Robert Brown", date: "2024-05-22", quantity: 2, total: 1500.00 },
    { id: "SALE-004", productId: "PROD-2024-001", productName: "High-Density LED Striplight 240L", customerName: "Emily White", date: "2024-05-22", quantity: 3, total: 450.00 },
    { id: "SALE-005", productId: "PROD-2024-006", productName: "Compact Power Supply 60W", customerName: "Michael Green", date: "2024-05-23", quantity: 8, total: 3600.00 },
];

export const invoices: Invoice[] = [
  { id: "INV-2024-001", customerName: "John Doe", date: "2024-05-20", amount: 750.00, status: 'Paid' },
  { id: "INV-2024-002", customerName: "Jane Smith", date: "2024-05-21", amount: 850.00, status: 'Paid' },
  { id: "INV-2024-003", customerName: "Robert Brown", date: "2024-05-22", amount: 1500.00, status: 'Pending' },
  { id: "INV-2024-004", customerName: "Emily White", date: "2024-05-22", amount: 450.00, status: 'Overdue' },
  { id: "INV-2024-005", customerName: "Michael Green", date: "2024-05-23", amount: 3600.00, status: 'Pending' },
];

export const suppliers: Supplier[] = [
    {
        id: "SUP-001",
        name: "LED Innovations Inc.",
        contact: { name: "Mark Reyes", email: "mark.reyes@ledinnovations.com", phone: "0917-123-4567" },
        address: "123 Tech Drive, Silicon Valley, Cyberzone",
        contractTerms: "Net 30"
    },
    {
        id: "SUP-002",
        name: "Power Solutions Co.",
        contact: { name: "Anna Cruz", email: "anna.cruz@powersolutions.com", phone: "0918-987-6543" },
        address: "456 Industrial Park, Electron City",
        contractTerms: "Net 60"
    },
    {
        id: "SUP-003",
        name: "AluPro Extrusions",
        contact: { name: "Ben Tan", email: "ben.tan@alupro.com", phone: "0922-555-1234" },
        address: "789 Metal Works Ave, Alloy Town",
        contractTerms: "COD"
    },
     {
        id: "SUP-004",
        name: "Bright Home Lighting",
        contact: { name: "Carla Lim", email: "carla.lim@brighthome.com", phone: "0925-888-5678" },
        address: "101 Illumination St, Light City",
        contractTerms: "Net 45"
    }
];

export const users: User[] = [
    {
        id: "USR-001",
        name: "Admin User",
        email: "admin@example.com",
        role: "Admin",
        status: "active",
        lastLoginAt: "2024-05-23T10:00:00Z",
        createdAt: "2024-01-01T10:00:00Z"
    },
    {
        id: "USR-002",
        name: "John Inventory",
        email: "john.inventory@example.com",
        role: "Inventory Manager",
        status: "active",
        lastLoginAt: "2024-05-22T15:30:00Z",
        createdAt: "2024-02-15T11:00:00Z"
    },
    {
        id: "USR-003",
        name: "Sally Sales",
        email: "sally.sales@example.com",
        role: "Sales",
        status: "active",
        lastLoginAt: "2024-05-23T09:00:00Z",
        createdAt: "2024-02-15T11:05:00Z"
    },
    {
        id: "USR-004",
        name: "Peter Purchase",
        email: "peter.purchase@example.com",
        role: "Purchasing",
        status: "inactive",
        lastLoginAt: "2024-04-10T12:00:00Z",
        createdAt: "2024-03-01T14:00:00Z"
    }
];
